### ISSUE TITLE
Import error in spatial cells 

### ISSUE THREAD

**Issue by yas92** [SemenovLab/SpaCells#20]
![Import error SpatialCells](https://github.com/SemenovLab/SpatialCells/assets/126460163/4fabce9d-3017-4faf-9fd1-f3c4403f3606)
I have found this error while trying to import, inside the file"--importRegion.py" did not have function "from_geojason".

**Comment by bscrow** [comment]
Hi @yas92 can I check which version of shapely do you have installed? 

SpatialCells depends on shapely version >= 2.0.0

**Comment by haymar92** [comment]
![shapely error](https://github.com/SemenovLab/SpatialCells/assets/126460163/f6365f6e-770c-44de-b720-9659b4742715)
![image](https://github.com/SemenovLab/SpatialCells/assets/126460163/3cfb5a41-357e-413a-8ff2-9f0b088ef6b2)
I am using python version 3.10 and could you please instruct me which version should I use?

**Comment by bscrow** [comment]
There seems to be a typo. pip install shapely>=2.0.0 without spaces should resolve the issue. 

It is a known issue that some of scimap's features depend on shapely<2.0.0, but the version seems to have been updated on github. If this dependency issue affects your analysis workflow, I would recommend installing SpatialCells in a separate conda environment for now.
